steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartsystem-api:$BUILD_ID
      - -f
      - backend/Dockerfile
      - backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartsystem-api:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - smartsystem
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartsystem-api:$BUILD_ID
      - --region
      - europe-west1
      - --platform
      - managed
      - --quiet

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartsystem-api:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
