# Generated by Django 5.2.8 on 2025-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_department_alter_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
