# Generated by Django 5.2.8 on 2025-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
