# Generated by Django 5.2.8 on 2025-12-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='base_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='duplicate_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='used_ai',
            field=models.BooleanField(default=False),
        ),
    ]
