# Generated by Django 5.2.8 on 2025-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_base_complaint_complaint_duplicate_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='in_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
