# Generated by Django 5.2.8 on 2025-12-21 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_ai_summary', models.BooleanField(default=True)),
                ('use_ai_routing', models.BooleanField(default=True)),
                ('use_duplicate_detection', models.BooleanField(default=True)),
                ('ai_min_confidence', models.FloatField(default=0.5, help_text='Minimum confidence from AI to accept department routing.')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Similarity (0–1) above which a complaint is considered duplicate.')),
                ('spam_max_per_day', models.PositiveIntegerField(default=20, help_text='Max complaints per user per day before considered spam.')),
                ('spam_max_per_hour', models.PositiveIntegerField(default=10, help_text='Max complaints per user per hour before considered spam.')),
                ('allow_citizen_registration', models.BooleanField(default=True, help_text='If false, new citizens cannot register.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('citizen', 'Citizen')], default='citizen', max_length=20)),
                ('national_id', models.CharField(blank=True, help_text='11-digit national ID for citizens.', max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'National ID must be 11 digits.'), django.core.validators.RegexValidator('^\\d{11}$', 'National ID must contain exactly 11 digits.')])),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_spammer', models.BooleanField(default=False)),
                ('can_read_complaints', models.BooleanField(default=False)),
                ('can_update_complaints', models.BooleanField(default=False)),
                ('can_reply_complaints', models.BooleanField(default=False)),
                ('can_manage_departments', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_ai_settings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
