# Generated by Django 5.2.8 on 2025-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_closed_at_complaint_in_review_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, help_text="view_scope = 'assigned' ise erişebileceği birimler.", related_name='staff_profiles', to='complaints.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_scope',
            field=models.CharField(choices=[('all', 'Tüm şikâyetler'), ('assigned', 'Sadece atanmış birimler'), ('unassigned', 'Sadece birimi olmayan şikâyetler')], default='all', help_text="Personelin hangi şikâyetleri görebileceğini belirler: 'all' = tümü, 'assigned' = sadece atanmış birimler, 'unassigned' = sadece birimi olmayan şikâyetler.", max_length=20),
        ),
    ]
